In [1]:
my_string = 'Hello world, I am learning #ML'

In [ ]:
print (1+2)

In [14]:
print(my_string.upper())

HELLO WORLD, I AM LEARNING #ML


.pop removes from list by index
.remove removes from list by passing the string
.clear removes all objects
del string [index] removes by index

sets use curly braces but not semi-colons. This is the difference from dictionary

while loop

In [15]:
# first initialise
count = 1

# then the condition
while count <= 4:
    # the implication
    print('count is:' f'{count}')
    
    #lastly the step/proceedure
    count += 1

count is:1
count is:2
count is:3
count is:4


In [16]:
item = 0
while item < 5:
    print (item)
    item += 1

0
1
2
3
4


In [17]:
item = 0
while item < 5:
    item = item + 1
    print (item)

1
2
3
4
5


In [3]:
import numpy as np

In [22]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [23]:
# identity matrix
np.eye (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.random.randn(x) #gives x random numbers from uniform distribution i.e. numbers between 0 & 1

In [24]:
np.random.rand(10)

array([0.92417445, 0.29096539, 0.9061451 , 0.76480346, 0.52603711,
       0.3398373 , 0.56042708, 0.21759763, 0.46566488, 0.86793679])

In [25]:
np.random.rand(10,5,5)

array([[[0.63716265, 0.46688506, 0.677441  , 0.10789721, 0.2999901 ],
        [0.92228592, 0.87284562, 0.0523386 , 0.36777582, 0.56013029],
        [0.59013262, 0.44119086, 0.01628135, 0.52255839, 0.41122206],
        [0.18299441, 0.08816625, 0.29283714, 0.24131996, 0.09212058],
        [0.50929168, 0.32020204, 0.21403557, 0.24577483, 0.26989065]],

       [[0.29336424, 0.17948419, 0.72931058, 0.3118198 , 0.52885237],
        [0.73870254, 0.99359716, 0.39097154, 0.88054721, 0.17438559],
        [0.34899164, 0.10806978, 0.23889979, 0.84869978, 0.7448228 ],
        [0.05674625, 0.74324795, 0.91478902, 0.53781585, 0.24931994],
        [0.83983996, 0.31439865, 0.33729231, 0.65829813, 0.19406899]],

       [[0.46307302, 0.42155435, 0.79035048, 0.93940766, 0.77516674],
        [0.04775369, 0.6292209 , 0.40805578, 0.23661663, 0.47642147],
        [0.63328528, 0.41430353, 0.84025452, 0.59366565, 0.85148791],
        [0.57890791, 0.14213539, 0.67177223, 0.17791648, 0.84081164],
        [0.79055

In [43]:
np.random.randint(1,5)

1

In [99]:
np.random.randint(1,5, size =10)

array([1, 1, 2, 3, 3, 3, 2, 1, 3, 3])

In [101]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [103]:
y[[0,1,2]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
y[[0,1,0]]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [105]:
y[[0,1,2][0]]

array([1, 2, 3])

In [111]:
y[[0,1,2],[0,1,0]]

array([1, 5, 7])